# Generated by Django 3.1.2 on 2020-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201009_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
