# Generated by Django 3.1.2 on 2020-10-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_jobexperience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
