# Generated by Django 3.1.2 on 2020-11-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20201101_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JourneySteps',
            new_name='JourneyStep',
        ),
    ]
