# Generated by Django 3.1.2 on 2020-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20201101_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='journeys/'),
        ),
    ]
