# Generated by Django 3.1.2 on 2020-11-02 05:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20201101_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tech_used', models.TextField(null=True)),
                ('lessons_learned', models.TextField(null=True)),
                ('to_do', models.TextField(null=True)),
                ('detailed_description', models.TextField(null=True)),
                ('cover_image', models.ImageField(null=True, upload_to='projects/')),
                ('test_mce_field', tinymce.models.HTMLField()),
            ],
        ),
    ]
