# Generated by Django 3.1.2 on 2020-11-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
