# Generated by Django 3.1.2 on 2020-11-02 06:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20201102_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test_mce_field',
        ),
        migrations.AddField(
            model_name='project',
            name='accomplished',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='detailed_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lessons_learned',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_used',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='to_do',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
