# Generated by Django 3.1.2 on 2020-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystep',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
