# Generated by Django 3.1.2 on 2020-11-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20201102_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='link',
            field=models.URLField(),
        ),
    ]
