# Generated by Django 3.1.2 on 2020-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20201102_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
