# Generated by Django 3.1.2 on 2020-11-02 15:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_auto_20201102_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='title',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
