# Generated by Django 3.1.2 on 2020-11-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_auto_20201102_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
