# Generated by Django 3.1.2 on 2021-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_auto_20210122_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='connect/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
