# Generated by Django 3.1.2 on 2021-02-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystep',
            name='display_order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
